"area: elementary":
  - changed-files:
    - any-glob-to-any-file: elementary/**

"area: satisfactory":
  - changed-files:
    - any-glob-to-any-file: satisfactory/**

"area: utilitary":
  - changed-files:
    - any-glob-to-any-file: utilitary/**

"area: infrastructure":
  - changed-files:
    - any-glob-to-any-file: .github/**
